# HOWTO: https://pre-commit.com/#usage
# dnf install pre-commit
# pre-commit install -t pre-commit -t pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
  - repo: https://github.com/PeterMosmans/jenkinslint
    rev: v1.0.0
    hooks:
      - id: jenkinslint

ci:
  autoupdate_schedule: quarterly
